import type { ScheduledShiftsData } from "./types/scheduled-shifts-response";
import type { Employee } from "./types/employee";

export const mockScheduledShiftsData: ScheduledShiftsData = {
  payroll_codes: [
    {
      id: 1,
      display_code: "REG",
      desc: "Regular Hours",
      classification: ["Regular"],
    },
    {
      id: 2,
      display_code: "VAC",
      desc: "Vacation",
      classification: ["Planned Leave"],
    },
  ],
  occupations: [
    {
      id: 101,
      display_str: "RN",
      union: 1,
      occupation_class: 1,
      job_code: 1234,
      long_description: "Registered Nurse",
      desc: "RN",
      links: {
        home_assignments: "/api/assignments/101",
        employees: "/api/employees/101",
      },
    },
  ],
  region_departments: [
    {
      id: 201,
      identifier: "",
      name: "region_departments.201.name",
      short_name: "",
      facility: {
        id: 301,
        name: "",
        short_name: "",
        display_str: "",
      },
      scheduling_team: {
        name: "VGH Medical",
        display_str: "VGH Medical Team",
        sorting_index: 1,
        visible_in_regional_dashboard: true,
      },
      phone_number: "250-555-1234",
      fallback_email: "vgh3s@hospital.ca",
      time_zone: "America/Vancouver",
      display_str: "VGH 3 South",
      links: {
        employees: "",
        union_department_rules: "",
      },
    },
  ],
  scheduled_shifts: [
    {
      display_str: "Day Shift",
      id: 1001,
      shift_icon: "D",
      shift_class: "day",
      payroll_code: 1,
      start_timestamp: "2024-01-15T07:30:00-08:00",
      end_timestamp: "2024-01-15T19:30:00-08:00",
      occupation: 101,
      department: 201,
      employee: 401,
      duration_hours: 12,
      date: "2024-01-15",
      external_reference_id: "",
    },
    {
      display_str: "Night Shift",
      id: 1002,
      shift_icon: "N",
      shift_class: "night",
      payroll_code: 1,
      start_timestamp: "2024-01-15T19:30:00-08:00",
      end_timestamp: "2024-01-16T07:30:00-08:00",
      occupation: 101,
      department: 201,
      employee: 401,
      duration_hours: 12,
      date: "2024-01-15",
      external_reference_id: "",
    },
    {
      display_str: "Vacation",
      id: 1003,
      shift_icon: "V",
      shift_class: "vacation",
      payroll_code: 2,
      start_timestamp: "2024-01-16T07:30:00-08:00",
      end_timestamp: "2024-01-16T19:30:00-08:00",
      occupation: 101,
      department: 201,
      employee: 401,
      duration_hours: 12,
      date: "2024-01-16",
      external_reference_id: "",
    },
  ],
  meta: {
    page: 1,
    per_page: 50,
    total_results: 1,
    total_pages: 1,
  },
};

export const mockEmployee: Employee = {
  id: 401,
  position_number: 12345,
  hsms_user: {
    id: 501,
    username: "username",
    first_name: "first_name",
    last_name: "last_name",
    personal_email: "",
    is_multiuser_guest: false,
    is_staff: false,
    is_active: true,
    is_registered: true,
    is_saml_login_enabled: true,
    is_hsms_login_enabled: true,
    current_user_profile: "Employee",
    joined_timestamp: "2023-01-01T00:00:00-08:00",
    first_login_timestamp: "2023-01-02T09:00:00-08:00",
    last_login_timestamp: "2024-01-15T08:00:00-08:00",
    number_of_successful_logins: 245,
    last_activity_timestamp: "2024-01-15T16:30:00-08:00",
    last_password_reset_timestamp: "2023-07-01T00:00:00-08:00",
    display_str: "",
  },
  union: 1,
  seniority_sort: 1000,
  seniority_display: "",
  vacation_bank_required_hours: 1950,
  employee_assignment_type: "Regular Full Time",
  additional_properties: "",
  home_occupation: 101,
  work_phone: "",
  contact_email: "employee@example.com",
  work_email: "employee@example.com",
  external_employee_number: "",
  display_str: "",
  links: {
    department: "",
  },
};
